/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.annotations.VeryImportant;
import org.example.classes.User;

public class App {
    public static void main(String[] args) {
        User user1 = new User("soufiane" , 22);
        if (user1.getClass().isAnnotationPresent(VeryImportant.class)){
            System.out.println("Very Important");
        }else {
            System.out.println("Not Important");
        }
    }
}
